language: go
go: 
 - 1.4
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain -osarch="$OS_ARCH"
  - go get github.com/tcnksm/ghr
after_success:
  - gox -osarch="$OS_ARCH" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr -u $GITHUB_USER -t $GITHUB_TOKEN --replace v0.4.0 dist/